#!/bin/bash
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

rm -rf constant/polyMesh/sets 



#runApplication surfaceTransformPoints -scale '(1e-6 1e-6 1e-6)' constant/triSurface/ellip1.stl constant/triSurface/ellip.stl


runApplication blockMesh
runApplication surfaceFeatureExtract

runApplication snappyHexMesh -overwrite

#runApplication transformPoints -scale '(1e-6 1e-6 1e-6)'

# Restore initial fields
restore0Dir

runApplication splitMeshRegions -cellZones -overwrite

# Remove fluid fields from solid regions (important for post-processing)

for region in $(foamListRegions solid)
do
    rm -f 0/$region/{nut,alphat,epsilon,k,U,p_rgh}
    rm -f processor*/0/$region/{nut,alphat,epsilon,k,U,p_rgh}
done

for region in $(foamListRegions)
do
    runApplication -s $region changeDictionary -region $region
done












#------------------------------------------------------------------------------
